### ISSUE TITLE
Crashes on Game Load

### ISSUE THREAD

**Issue by Morningate** [BuiltBrokenModding/SBM-CharcoalBlock#2] opened 2020-08-22 17:27 UTC
Thanks for updating the mod to 1.16.2. Unfortunately, the game is crashing when I attempt to load it with this mod installed.  I have removed all other mods and tried to load the game with only this mod installed, but the game still crashes. Forge isn't putting out a crash report when it happens, either. I am using the following:

MC 1.16.2
Forge for 1.16.2: 33.0.20
SBM-CharcoalBlock-1.16.2-1.0.0

Thanks for your hard work!

**Comment by kreezxil** [comment] 2021-01-01 20:54
I'm getting a crash too, it says the license has invalid characters after it as indicated in line 92 of the attached debug.log

https://gist.github.com/kreezxil/640bebdc7a9150cd2864bd34ed679e88#file-gistfile1-txt-L92

**Comment by kreezxil** [comment] 2021-01-01 20:57
You're missing a trailing quote on line 6 of this file. https://github.com/BuiltBrokenModding/SBM-CharcoalBlock/blob/1.16/src/main/resources/META-INF/mods.toml#L6

**Comment by DarkGuardsman** [comment] 2021-04-20 10:04
Is this still an issue?

**Comment by kreezxil** [comment] 2021-04-20 15:30
idk, i didn't wait 3 months to find out.

just close it out and let someone reopen if it happens again. That's what i do on projects where the issue is 6 months old or older.

**Comment by DarkGuardsman** [comment] 2021-04-20 20:20
K, just wanted to check before we closed it... just now getting around to cleaning up all 200+ github repo issue trackers I have :)

**Closed as completed by DarkGuardsman** 2021-04-20 20:20 UTC
Labels: bug
